name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix['node-version'] }}
          registry-url: 'https://registry.npmjs.org/'
        
      - name: Install dependencies
        run: npm install

      - name: Build Valaxy Blog
        run: npm run build
      
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: ${{ secrets.SFTP_SERVER_DIR }}
          sftpArgs: '-o ConnectTimeout=5'
          delete_remote_files: true
          sftp_only: true