name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix['node-version'] }}
          registry-url: 'https://registry.npmjs.org/'
        
      - name: Install dependencies
        run: npm install

      - name: Build Valaxy Blog
        run: npm run build
      
      - name: Start SSH Agent and Load Private Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}
          known-hosts-file: /dev/null
        
      - name: Deploy files via SCP
        run: |
          echo "Starting SCP deployment..."
          scp -r \
            -P ${{ secrets.SFTP_PORT }} \
            -o StrictHostKeyChecking=no \
            ./dist/* \
            ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:${{ secrets.SFTP_SERVER_DIR }}
          echo "SCP deployment completed."